version: "3.3"

services:
    lambda:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BASEIMAGE: lambci/lambda:build-python3.7
        image: cirrusgeo/run-lambda:latest
    geolambda:
        build:
            context: .
            args:
                BASEIMAGE: developmentseed/geolambda:2.1.0-python
        image: cirrusgeo/run-geolambda:latest
    geodatalambda:
        build:
            context: .
            dockerfile: ./data_geo/Dockerfile
            args:
                BASEIMAGE: developmentseed/geolambda:2.1.0-python
        image: cirrusgeo/run-geodatalambda:latest

